export const Global = {
  companyid: null,
  workshopId: null,
  accessToken: null,
  changeView: null,
  accident: null,
  Openbadge: null,
  Closebadge: null,
  Deletebadge: null,
  badgeicon: null,
  requestid: null,
  employeeid: null,
  accidentid: null,
  statusId: null,
  accident: null,
  closedApi: null,
  deleteApi: null,
  parameter: null,
  appversion: null,
  mobileid: null,
  AccidentID: null,
  accidentHistoryIcon: null,
  apiurl: 'https://qapi.joclaims.com/',
};
