import LocalizedStrings from 'react-native-localization';
// export const DEFAULT_LANGUAGE = 'ar';
// import en from './en.js';
// import ar from './ar.js';
const Strings = new LocalizedStrings({
  ar: {
    loginbutton: 'دخول',
    signoutbutton: 'خروج',
    forgetpassword: 'نسيت كلمة المرور ؟',
    sendemail: 'ارسل بريد الكتروني',
    emailphone: 'البريد الإلكتروني',
    Password: ' كلمة المرور',
    //Bottem Tabs
    request: 'الطلبات',
    history: 'ارشيف',
    accidents: 'الحوادث',
    accidentHistory: 'ارشيف الحوادث',
    //Screentabs
    orderplaced: 'الطلبات المقدمة',
    delivered: 'استلام',
    paid: 'مدفوع ',
    cancelled: 'ألغيت',
    closed: 'مغلق',
    deleted: 'تم الحذف',
    open: 'مفتوح ',
    Toastemail: 'بريد إلكتروني خاطئ',
    Toastpassword: 'كلمة المرور غير صحيحة',
    cancel: 'حذف',
    areyousure: 'هل ترغب بالخروج؟هل أنت واثق؟',
    wanttologout: 'هل ترغب بالخروج؟',
    confirm: 'صدق',
    logiSuccessful: 'تم تسجيل الدخول بنجاح',
    invalidLogin: 'تسجيل الدخول غير صالح',
    //drawer
    home: 'بيت',
    userprofile: 'ملف شخصي',
    settings: 'الإعدادات',
    //Request Tab strings
    CarIsReady: 'المركبه جاهزه',
    workshomeName: 'اسم ورشة العمل:',
    requestNumber: 'رقم الطلب:',
    accidentNo: 'رقم الحادث:',
    VIN: 'رقم الشاصي:',
    plateNO: 'رقم اللوحة:',
    poAmount: 'قيمة طلب الشراء:',
    //userProfile Tab Strings
    workshopOwner: 'صاحب ورشه عمل:',
    phone: 'الهاتف:',
    email: 'البريد الالكتروني:',
    esignature: 'التوقيع الإلكتروني:',
    employeePermisions: 'أذونات الموظفين:',
    addaccidentParts: ' أضف أجزاء الحادث:',
    receiveParts: ' تلقي أجزاء:',
    repairCar: ' يصلح السيارة:',
    //Accident tab Strings
    accidentType: 'نوع الحادث:',
    CreatedBy: 'انشأ من قبل:',
    VehicleOwnerName: 'اسم مالك المركب:',
    //open Accident strings
    WorkShopOwner: 'صاحب الورشة',
    carDetails: 'تفاصيل السيارة',
    additionalAccidentDetails: '',
    WorkshopDetail: 'ورشة عمل التفاصيل',
    faultyCompanyName: 'اسم الشركة المتسببه:',
    numberofCarsInvolved: 'عدد المركبات المتضرره في الحادث:',
    accidentNumber: 'رقم الحادث:',
    bodyType: 'نوع الجسم:',
    responsibility: 'المسؤوليه:',
    workShopName: 'اسم ورشة العمل:',
    carNotes: 'ملاحظات المركبه:',
    accidentDetails: '',
    DamagePartsDetails: '',
    accidentHappendOn: 'تاريخ وقوع الحادث:',
    engineType: 'نوع المحرك:',
    markers: 'علامات:',
    //updateAccident
    updateAccident: 'تحديث حادث',
    comprehensive: 'تأمين شامل',
    thirdPartyLiability: 'تامين الزامي',
    faulty: 'متسبب',
    nonFaulty: 'متضرر',
    mutualResponsibility: 'مشترك',
    pricingType: 'نوع التسعير',
    pricingAndProviding: 'تسعير و توفير',
    pricingOnly: 'تسعير فقط',
    accidentMarker: 'علامات الحوادث',
    accidentContainer: 'ملاحظات الحادث',
    workShopFinding: 'تقرير الكراج',
    note: 'ملاحظة',
    //workshopFinding
    name: 'الاسم',
    quantity: 'العدد',
    condition: 'الحالة',
    new: 'جديد',
    used: 'مستعمل',
    any: 'أيهما',
    original: 'الأصلي',
    afterMarket: 'تجاري',
    addparts: 'إضافة قطعة',
    uploadImage: 'تحميل الصورة',
    model: 'الصنف',
    quotationDetailYear: 'سنة الصنع',
    Year: 'سنة',
    viewAccidentInfo: 'مشاهده معلومات الحادث',

    YES: 'نعم',
    NO: 'لا',
    AVAILABLE: 'متوفر',
    DELETE: 'حذف',
    CANCEL: 'إلغاء',
    PRICE: ' السعر',
    COST: 'السعر',
    DAYS: ' ايام',
    DAY: 'يوم',
    NEED_AN_ORDER: 'تحتاج إلى طلب',
    AVAILABLE_NOW: 'متوفر الآن',
    AVAILABILITY: 'التوفّر',
    Max_QUANTITY: 'أقصى العدد',
    PROGRESS: 'التقدم',
    TOTAL_TEXT: 'مجموع',
    IN_PROGRESS_TEXT: 'قيد التنفيذ',
    REFERRED_TEXT: 'المحالة',
    PENDING_APPROVAL_TEXT: 'قيد الموافقة',
    ORDERED_TEXT: 'تم الطلب',
    DELIVERED_TEXT: 'استلام',
    CLOSED_TEXT: 'مغلق',
    NO_RECORD_FOUND: 'لم يتم العثور على سجل',
    QUOTATION_DETAIL: 'التفاصيل',
    PLEASE_WAIT_TEXT: 'الرجاء الانتظار...',
    CAR: ' السيارة',
    REQUIRED_PART: 'الجزء المطلوب',
    PIECE: 'قطع',
    PIECES: 'قطعة',
    TostInvalidLoginCredential: 'بيانات تسجيل الدخول غير الصالحة',
    SplashString: 'حلول إلكترونية لمطالبات شركات التأمين',
    TOAST_REGISTERED_SUCCESSFULLY: 'تم التسجيل بنجاح',
    TOAST_CREDENTIAL_EXISTS: 'البريد الإلكتروني / الهاتف موجود بالفعل',
    TOAST_SOMETHING_WRONG: 'هناك خطأ ما',
    toastInvalidEmail: 'بريد إلكتروني خاطئ',
  },
  en: {
    loginbutton: 'Login',
    signoutbutton: 'Signout',
    forgetpassword: 'Forget Password?',
    sendemail: 'Send Email',
    emailphone: 'Email/Phone',
    Password: 'Password',
    logiSuccessful: 'Login Successfull',
    invalidLogin: 'Invalid Login',
    //Bottem Tabs
    request: 'Request',
    history: 'History',
    accidents: 'Accidents',
    accidentHistory: 'ACCIDENT HISTORY',
    //Screentabs
    orderplaced: 'Order Placed',
    delivered: 'Delivered',
    paid: 'Paid',
    cancelled: 'Cancelled',
    closed: 'Closed',
    deleted: 'Deleted',
    open: 'Open',
    Toastemail: 'invalid email',
    Toastpassword: 'Password is not Correct',
    cancel: 'Cancel',
    areyousure: 'Are you sure? Do you want to logout?',
    wanttologout: 'Do you want to logout?',
    confirm: 'Confirm',
    //drawer
    home: 'Home',
    userprofile: 'User Profile',
    settings: 'Settings',
    //Request Tab strings
    CarIsReady: 'Car Is Ready',
    workshomeName: 'Workshome name:',
    requestNumber: 'Request Number:',
    accidentNo: 'Accident No:',
    VIN: 'VIN:',
    plateNO: 'Plate NO:',
    poAmount: 'PO Amount:',
    //userProfile Tab Strings
    workshopOwner: 'Workshop Owner',
    phone: 'Phone',
    email: 'EMAIL',
    esignature: 'Esignature',
    employeePermisions: 'EmployeePermisions',
    addaccidentParts: 'Add accident parts',
    receiveParts: 'Receive parts',
    repairCar: 'Repair car',
    //Accident tab Strings
    accidentType: ' Accident Type:',
    CreatedBy: 'Created By:',
    VehicleOwnerName: 'Vehicle Owner Name:',
    //open Accident Detail
    // workshopOwner: '',
    carDetails: 'Car Details',
    additionalAccidentDetails: 'Additional Accident Details:',
    WorkshopDetail: 'Workshop Detail:',
    faultyCompanyName: 'Faulty Company Name:',
    numberofCarsInvolved: 'Number of Cars Involved:',
    accidentNumber: 'Accident Number:',
    bodyType: 'Body Type:',
    responsibility: 'Responsibility:',
    workShopName: 'Work Shop Name:',
    carNotes: 'Car notes:',
    accidentDetails: 'Accident Details:',
    DamagePartsDetails: 'Damage Parts Details',
    accidentHappendOn: 'Accident Happend On:',
    engineType: 'Engine Type:',
    markers: 'Markers',
    //updateAccident
    updateAccident: 'Update Accident',
    comprehensive: 'Comprehensive',
    thirdPartyLiability: ' Third Party Liability',
    faulty: ' Faulty',
    nonFaulty: ' Non-Faulty',
    mutualResponsibility: ' Mutual Responsibility',
    pricingType: ' Pricing Type',
    pricingAndProviding: ' pricing and providing',
    pricingOnly: ' pricing only',
    accidentMarker: 'Accident Marker',
    accidentContainer: 'Accident Container',
    workShopFinding: 'WorkShop Finding',
    note: 'Note',
    //workshopFinding
    name: 'Name',
    quantity: 'Quantity',
    condition: 'Condition',
    new: 'New',
    used: 'Used',
    any: 'Any',
    original: 'Origional',
    afterMarket: 'Aftermarket',
    addparts: 'Add Parts',
    uploadImage: 'Upload Image',
    model: 'Model',
    quotationDetailYear: 'Year',
    Year: 'Year',
    viewAccidentInfo: 'View AccidentInfo',
    TostInvalidLoginCredential: 'Invalid Login Credential',

    toastInvalidEmail: 'Invalid Email',
    SplashString: 'Automated solutions for auto insurance accident claims.',
    TOAST_REGISTERED_SUCCESSFULLY: 'تم التسجيل بنجاح',
    TOAST_CREDENTIAL_EXISTS: 'البريد الإلكتروني / الهاتف موجود بالفعل',
    TOAST_SOMETHING_WRONG: 'هناك خطأ ما',
  },
});

export default Strings;
